# Generated by Django 5.1.2 on 2024-10-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='quotes',
            field=models.ManyToManyField(to='quotesapp.quote'),
        ),
    ]
