# Generated by Django 5.1.2 on 2024-10-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0002_tag_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
