# Generated by Django 5.1.2 on 2024-10-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0006_remove_tag_quotes_alter_quote_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='quotes',
            field=models.ManyToManyField(to='quotesapp.quote'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(to='quotesapp.tag'),
        ),
    ]
