# Generated by Django 5.1.2 on 2024-10-29 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0010_tag_tag_of_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='quotes',
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotesapp.author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(related_name='quotes', to='quotesapp.tag'),
        ),
    ]
